---
deployment:
  tasks:
    - export DEPLOYPATH=/home5/bawaliiz/public_html/yamoonbaby.com/
    - /bin/cp -f index.html $DEPLOYPATH
    - /bin/cp -f index.php $DEPLOYPATH
    - /bin/cp -f raffle.html $DEPLOYPATH
    - /bin/cp -f jordan-areas.js $DEPLOYPATH
    - /bin/cp -f styles.css $DEPLOYPATH
